### ISSUE TITLE
Error when running CreateSnapshotsTable migration

### ISSUE THREAD

**Issue by travisdock** [westonganger/active_snapshot#23]
Rails 7.0.3.1
Ruby 3.0.3
mysql2 0.5.3

I ran `rails generate active_snapshot:install` and when I ran the resulting migration it failed with `wrong number of arguments (given 2, expected 1)`
I removed the brackets so that it now reads
`create_table :snapshots, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci" do |t|`
and everything works as expected. I don't know if there was an update in syntax. It appears `create_table` only expects one hash argument.

I can open a PR if you want me to but thought I would open this as an issue first.

Closed by #24

**Comment by westonganger** [comment]
Yes a PR would be appreciated. Thanks
