### ISSUE TITLE
How to track Mobility translated attributes and Action Text?

### ISSUE THREAD

**Issue by sedubois** [westonganger/active_snapshot#45]
Thank you for this gem! I am evaluating it to track attributes which PaperTrail does not track properly.

Using [Mobility](https://github.com/shioyama/mobility), with the default installation (key-value backend), how do I track translated attributes (without having conflicts between different locales and in a way where records can be restored)?

I tried this:

```ruby
class Page < ApplicationRecord
  extend Mobility
  include ActiveSnapshot
  translates :title, backend: :key_value, type: :string

  has_snapshot_children do
    instance = self.class.includes(:string_translations).find(id)
    { string_translations: instance.string_translations }
  end
end
```

If I have e.g. 2 locales and ensure that the page has a `title` value in each of those 2 locales, then calling `snapshot = page.create_snapshot!` successfully creates 3 snapshot items: one for the main record and one for each of the associated string_translations. This is good news because I hadn't managed to do this so far with Paper Trail or Audited (but I would be happy to be proven wrong.)

However when calling `snapshot.restore!` I get the error `PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "pages_pkey"`.

Questions:
- How to fix the reification error?
- Would there be a way to track the logical `title` attribute instead of referring to `string_translations` which is meant to be an implementation detail? As the name suggests, Mobility is supposed to allow flexibly using different types of backends and the association name `string_translations` is only applicable to its key-value backend.
- From a logical standpoint, these translations aren't really children. The page's title isn't a "child" of the page but an attribute of the page. Would it make more sense to rename `has_snapshot_children` to `has_associated_snapshots` or similar?
- Similar question as in the Mobility example above but for Rails Action Text rich texts: they are similarly stored in a separate table using polymorphic relationship. How to track those? 

Finally, I need to combine all 3 aspects: snapshots for Action Text rich texts which are translated. I manage to translate Action Text rich texts using [this gem](https://github.com/sedubois/mobility-actiontext/) I built. I could try combining it with this gem when I have more clarifications on the questions above.

**Comment by sedubois** [comment]
Here is a demo for Action Text:

```ruby
class Page < ApplicationRecord
  include ActiveSnapshot
  has_rich_text :body
  has_snapshot_children do
    instance = self.class.includes(:rich_text_body).find(id)
    { rich_text_body: instance.rich_text_body }
  end
end
```

I manage to create the snapshot but again not to restore it.

**Comment by sedubois** [comment]
Demo with _translated_ Action Text:

```ruby
class Page < ApplicationRecord
  extend Mobility
  include ActiveSnapshot
  translates :body, backend: :action_text # Using https://github.com/sedubois/mobility-actiontext/
  has_snapshot_children do
    instance = self.class.includes(:rich_text_body).find(id)
    { rich_text_body: instance.rich_text_body }
  end
end
```

**Comment by westonganger** [comment]
I feel that in this scenario you should take this gems code and copy it into your project, remove it from the gemfile and then customize it for your individual applications needs. This is described in the README:

> read this gems brief source code completely before use OR copy the code straight into your codebase
