### ISSUE TITLE
Feature request: storing the snapshot's JSON in ActiveStorage (AWS S3) instead of the database

### ISSUE THREAD

**Issue by feliperaul** [westonganger/active_snapshot#48]
First of all, this gem brings a fresh approach to version tracking and I love it! Very well written, congrats.

When using version tracking, specially with heavy models (think long text / html documents, where each save creates a snapshot), the number of versions tracked can really start bloating up the database.

Even if the developer is considerate with the settings (how long and how many versions are tracked), I still think that only the Snapshots (which are the 'metadata' of each version) need to be in the database; the actual JSON of the models stored could be stored in S3 and fetched only when needed.

This is because, in general, version tracking UI is not used frequently by the users; it's often a 'backup restore' kinda of feature. 

So the user can tolerate a few extra ms of latency when fetching versions, and I think that even holds when you are comparing the JSON between two versions for some diffing. 

Do you think supporting ActiveStorage storage of the JSON blobs would be something to be implemented in the feature, as an option for the user, being configured on a per-model basis?

**Comment by westonganger** [comment]
@feliperaul I think that this is a cool idea and would be interested in a PR which implements this.

**Comment by westonganger** [comment]
Closing this until someone attempt to implement this.

As of right now I feel theres no need for this optimization so its not likely to get implemented anytime soon.
