### ISSUE TITLE
SnapshotItem: presence validation for object column

### ISSUE THREAD

**Issue by dmrAnderson** [westonganger/active_snapshot#51]
According to the **migration file**:
https://github.com/westonganger/active_snapshot/blob/5851156597bb1733a46bbe88e23579936731aa04/lib/generators/active_snapshot/install/templates/create_snapshots_tables.rb.erb#L21
It would be a pleasure to have a `validation` for this on a `model` level.

_If it simplifies the process, I can take this ticket to create a PR independently._

**Comment by westonganger** [comment]
You are right that it might be more comprehensive to have that model-level validation (mainly from the perspective of reading the codebase and understanding the models)

But first @dmrAnderson can I understand your use case?

When I look at the current codebase I see that we are using `upsert_all` 

https://github.com/westonganger/active_snapshot/blob/5322893cd97b7f08832f07cf266ac494fcd3428a/lib/active_snapshot/models/concerns/snapshots_concern.rb#L45

`upsert_all` does not perform any model validations

So I assume you must have some custom code that you are using?

**Comment by dmrAnderson** [comment]
I’ve been exploring the gem and came across this point, it was a simple play session from the console 😄 .
Yep, I noticed we’re using `upsert_all`, but since `SnapshotItem` inherits from `ActiveRecord::Base`, we can leverage other functionalities to check record validity or interact with the database.

**Comment by westonganger** [comment]
Ok I suppose that I would probably accept a PR that adds this.

Though I would still like to see some example code that demonstrates a real use-case for this

**Comment by westonganger** [comment]
v0.5.0 is now released which contains this fix.
