### ISSUE TITLE
Recomendation: Missing Documentation on Pinning Serializer for ActiveSnapshot

### ISSUE THREAD

**Issue by diogolsq** [westonganger/active_snapshot#68]
Hi there,  I think would be nice to have a section in the readme talking about pinning which serializer, active_snapshot runs with.

It would be helpful to include a section in the README explaining how to pin the serializer that ActiveSnapshot runs with. This would prevent issues when upgrading between versions, especially if the data serialization format changes significantly.

e.g

create an initialiser

```
ActiveSnapshot.config do |config|
  config.storage_method = "serialized_yaml"
end

```

Background

We recently upgraded ActiveSnapshot from version 0.2.4 to 0.3.2 and encountered problems due to changes in the data serialization format. Existing snapshots created with the old version were stored in an incompatible format, leading to unexpected behavior when reading or writing snapshots after the upgrade.

**Comment by westonganger** [comment]
@diogolsq Im sorry about the breakage in v0.3.0, however this was already documented in the upgrade instructions for v0.3.0 in the CHANGELOG.

https://github.com/westonganger/active_snapshot/blob/7228ce58566521e5eff55802d8d471b89809275b/CHANGELOG.md?plain=1#L49-L52

I recently removed mention of the configuration option (in v0.5.2) as the configuration option is only for legacy installations now. 

So far v0.3.0 was the only release that required manual intervention
