### ISSUE TITLE
Question about `has_snapshot_children` and reloading `self`

### ISSUE THREAD

**Issue by pjmartorell** [westonganger/active_snapshot#8]
In the documentation there is an example where `has_snapshot_children` reloads self from the database instead of using the instance that is already in memory. What is the reasoning behind this? Is it intended to avoid versioning associated records that are in memory and not persisted? or is it intended to take advantage of the eager-loading? or both things?
https://github.com/westonganger/active_snapshot/blob/23a769fbe1f42adecbb81edf015a0c5fc518767d/README.md#L89-L90

Thanks in advance for the clarification

**Comment by westonganger** [comment]
To take advantage of the eager loading but also gives a guaranteed clean slate.

**Comment by westonganger** [comment]
If you want to improve this comment feel free.
